export const ZODIAC_SIGNS = [
  { id: 1, name: 'Aries', sanskrit: 'Mesha', lord: 'Mars', symbol: '♈', element: 'Fire' },
  { id: 2, name: 'Taurus', sanskrit: 'Vrishabha', lord: 'Venus', symbol: '♉', element: 'Earth' },
  { id: 3, name: 'Gemini', sanskrit: 'Mithuna', lord: 'Mercury', symbol: '♊', element: 'Air' },
  { id: 4, name: 'Cancer', sanskrit: 'Karka', lord: 'Moon', symbol: '♋', element: 'Water' },
  { id: 5, name: 'Leo', sanskrit: 'Simha', lord: 'Sun', symbol: '♌', element: 'Fire' },
  { id: 6, name: 'Virgo', sanskrit: 'Kanya', lord: 'Mercury', symbol: '♍', element: 'Earth' },
  { id: 7, name: 'Libra', sanskrit: 'Tula', lord: 'Venus', symbol: '♎', element: 'Air' },
  { id: 8, name: 'Scorpio', sanskrit: 'Vrishchika', lord: 'Mars', symbol: '♏', element: 'Water' },
  { id: 9, name: 'Sagittarius', sanskrit: 'Dhanu', lord: 'Jupiter', symbol: '♐', element: 'Fire' },
  { id: 10, name: 'Capricorn', sanskrit: 'Makara', lord: 'Saturn', symbol: '♑', element: 'Earth' },
  { id: 11, name: 'Aquarius', sanskrit: 'Kumbha', lord: 'Saturn', symbol: '♒', element: 'Air' },
  { id: 12, name: 'Pisces', sanskrit: 'Meena', lord: 'Jupiter', symbol: '♓', element: 'Water' },
] as const;

export const NAKSHATRAS = [
  { index: 1, name: 'Ashwini', lord: 'Ketu', deity: 'Ashwini Kumaras' },
  { index: 2, name: 'Bharani', lord: 'Venus', deity: 'Yama' },
  { index: 3, name: 'Krittika', lord: 'Sun', deity: 'Agni' },
  { index: 4, name: 'Rohini', lord: 'Moon', deity: 'Brahma' },
  { index: 5, name: 'Mrigashira', lord: 'Mars', deity: 'Soma' },
  { index: 6, name: 'Ardra', lord: 'Rahu', deity: 'Rudra' },
  { index: 7, name: 'Punarvasu', lord: 'Jupiter', deity: 'Aditi' },
  { index: 8, name: 'Pushya', lord: 'Saturn', deity: 'Brihaspati' },
  { index: 9, name: 'Ashlesha', lord: 'Mercury', deity: 'Nagas' },
  { index: 10, name: 'Magha', lord: 'Ketu', deity: 'Pitris' },
  { index: 11, name: 'Purva Phalguni', lord: 'Venus', deity: 'Bhaga' },
  { index: 12, name: 'Uttara Phalguni', lord: 'Sun', deity: 'Aryaman' },
  { index: 13, name: 'Hasta', lord: 'Moon', deity: 'Savitr' },
  { index: 14, name: 'Chitra', lord: 'Mars', deity: 'Tvashtar' },
  { index: 15, name: 'Swati', lord: 'Rahu', deity: 'Vayu' },
  { index: 16, name: 'Vishakha', lord: 'Jupiter', deity: 'Indra-Agni' },
  { index: 17, name: 'Anuradha', lord: 'Saturn', deity: 'Mitra' },
  { index: 18, name: 'Jyeshtha', lord: 'Mercury', deity: 'Indra' },
  { index: 19, name: 'Mula', lord: 'Ketu', deity: 'Nirriti' },
  { index: 20, name: 'Purva Ashadha', lord: 'Venus', deity: 'Apas' },
  { index: 21, name: 'Uttara Ashadha', lord: 'Sun', deity: 'Vishvadevas' },
  { index: 22, name: 'Shravana', lord: 'Moon', deity: 'Vishnu' },
  { index: 23, name: 'Dhanishta', lord: 'Mars', deity: 'Vasus' },
  { index: 24, name: 'Shatabhisha', lord: 'Rahu', deity: 'Varuna' },
  { index: 25, name: 'Purva Bhadrapada', lord: 'Jupiter', deity: 'Aja Ekapada' },
  { index: 26, name: 'Uttara Bhadrapada', lord: 'Saturn', deity: 'Ahir Budhnya' },
  { index: 27, name: 'Revati', lord: 'Mercury', deity: 'Pushan' },
] as const;

export const PLANET_METADATA = {
  Ascendant: {
    name: 'Ascendant',
    sanskritName: 'Lagna',
    symbol: 'Asc',
    shortCode: 'Asc',
    isBenefic: true,
  },
  Sun: {
    name: 'Sun',
    sanskritName: 'Surya',
    symbol: '☉',
    shortCode: 'Su',
    isBenefic: false,
  },
  Moon: {
    name: 'Moon',
    sanskritName: 'Chandra',
    symbol: '☽',
    shortCode: 'Mo',
    isBenefic: true,
  },
  Mars: {
    name: 'Mars',
    sanskritName: 'Mangala',
    symbol: '♂',
    shortCode: 'Ma',
    isBenefic: false,
  },
  Mercury: {
    name: 'Mercury',
    sanskritName: 'Budha',
    symbol: '☿',
    shortCode: 'Me',
    isBenefic: true,
  },
  Jupiter: {
    name: 'Jupiter',
    sanskritName: 'Guru',
    symbol: '♃',
    shortCode: 'Ju',
    isBenefic: true,
  },
  Venus: {
    name: 'Venus',
    sanskritName: 'Shukra',
    symbol: '♀',
    shortCode: 'Ve',
    isBenefic: true,
  },
  Saturn: {
    name: 'Saturn',
    sanskritName: 'Shani',
    symbol: '♄',
    shortCode: 'Sa',
    isBenefic: false,
  },
  Rahu: {
    name: 'Rahu',
    sanskritName: 'Rahu',
    symbol: '☊',
    shortCode: 'Ra',
    isBenefic: false,
  },
  Ketu: {
    name: 'Ketu',
    sanskritName: 'Ketu',
    symbol: '☋',
    shortCode: 'Ke',
    isBenefic: false,
  },
} as const;
